### ISSUE TITLE
Missing map for DataWorker and SortWorker - Sveltekit

### ISSUE THREAD

**Issue by TravisThomp** [huggingface/gsplat.js#70]
Occasionally when developing with sveltekit these two 404 errors will occur.
```
SvelteKitError: Not found: /DataWorker.js.map
    at resolve (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\respond.js:522:13)
    at resolve (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\respond.js:322:5)
    at #options.hooks.handle (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\index.js:71:56)
    at Module.respond (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
SvelteKitError: Not found: /SortWorker.js.map
    at resolve (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\respond.js:522:13)
    at resolve (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\respond.js:322:5)
    at #options.hooks.handle (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\index.js:71:56)
    at Module.respond (E:\big_projects\gsplat-editor\node_modules\@sveltejs\kit\src\runtime\server\respond.js:319:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  text: 'Not Found'
}
```

I believe this is caused by a misconfiguration of `rollup-plugin-web-worker-loader` in the `rollupconfig.js`, I think the sourcemap parameter should be set to true on [this](https://github.com/huggingface/gsplat.js/blob/c7d1f8a3d97c570318e426c961c57cec3dfc61c5/rollup.config.js#L22C1-L22C53
) line
I haven't been able to reproduce this well enough to ensure that this fixes the issue but I'll report back when I can

**Comment by fcastrovilli** [comment]
same here!
